vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    categoryIcons:
      uri_prefix: /images/category/icons
      upload_destination: '%kernel.project_dir%/public/images/category/icons'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true